version: '3.7'
services:
  equipment-service-api:
    build: .
    image: equipment-service-api:v1
    ports:
      - "8081:8081"
    restart: always
    networks:
      - equipment-app
  equipment-service-front:
    build: ./front-end
    image: equipment-service-front:v1
    ports:
      - "3000:3000"
    restart: always
    networks:
      - equipment-app
networks:
  equipment-app: